### ISSUE TITLE
Не работает FTM -> Polygon

### ISSUE THREAD

**Issue by CrisBTC** [ryu666zaki/Stargate-Bridger#1]
Большое спасибо за скрипт , прямо громадное,. Матик - Фантом работает на ура , но к сожалению обратно он не работает , причем очень странно , когда он приступает к бриджу фантом -> матик , он вызывает контракт матика пытается списать средства от туда . 
Если есть возможность починить, будет супер. еще раз спасибо за скрипт

**Comment by lionff** [comment]
143 строка кода - начиная с swap_txn - polygon_w3 меняй на fantom_w3

**Comment by lionff** [comment]
и значение gas - тоже подмандрыч

**Comment by CrisBTC** [comment]
> 143 строка кода - начиная с swap_txn - polygon_w3 меняй на fantom_w3
спасибо громадное , уже прогресс, пошел апрув , но к сожалению не помогло,  но свап не делается, выскакивает ошибка 
"ValueError: {'code': -32000, 'message': 'invalid sender'}"
может ты сталкивался с такой

**Comment by lionff** [comment]
> > 143 строка кода - начиная с swap_txn - polygon_w3 меняй на fantom_w3
> 
> спасибо громадное , уже прогресс, пошел апрув , но к сожалению не помогло, но свап не делается, выскакивает ошибка `ValueError: {'code': -32000, 'message': 'invalid sender'}`
> 
> может ты сталкивался с такой

Неа, а сама транза так же не создалась? У меня по началу с количеством газа была фигня, его мало оказалось и транзы фейлились

**Comment by CrisBTC** [comment]
> > > 143 строка кода - начиная с swap_txn - polygon_w3 меняй на fantom_w3
> > 
> > 
> > спасибо громадное , уже прогресс, пошел апрув , но к сожалению не помогло, но свап не делается, выскакивает ошибка `ValueError: {'code': -32000, 'message': 'invalid sender'}`
> > может ты сталкивался с такой
> 
> Неа, а сама транза так же не создалась? У меня по началу с количеством газа была фигня, его мало оказалось и транзы фейлились

разобрался ))) там оказывается и имя функции надо было поменять, еще бы сделать баланс чтобы не целое число было и будет супер , а то палево какое то ))

**Comment by lionff** [comment]
> > > > 143 строка кода - начиная с swap_txn - polygon_w3 меняй на fantom_w3
> > > 
> > > 
> > > спасибо громадное , уже прогресс, пошел апрув , но к сожалению не помогло, но свап не делается, выскакивает ошибка `ValueError: {'code': -32000, 'message': 'invalid sender'}`
> > > может ты сталкивался с такой
> > 
> > 
> > Неа, а сама транза так же не создалась? У меня по началу с количеством газа была фигня, его мало оказалось и транзы фейлились
> 
> разобрался ))) там оказывается и имя функции надо было поменять, еще бы сделать баланс чтобы не целое число было и будет супер , а то палево какое то ))

8 строчка - AMOUNT_TO_SWAP = random.randint(35, 48) 
но надо добавить еще import random
можно зарандомить и не с целыми числами, но зачем?
Ты еще палишься на газ лимите, он выставлен константой, я себе подправил, чтоб брался актуальный + 20-30% сверху, чтоб транза точно прошла
Ну а по чесноку, если гонять только 2 направления - выглядит уже нехорошо в плане палева))

**Comment by CrisBTC** [comment]
> > > > > 143 строка кода - начиная с swap_txn - polygon_w3 меняй на fantom_w3
> > > > 
> > > > 
> > > > спасибо громадное , уже прогресс, пошел апрув , но к сожалению не помогло, но свап не делается, выскакивает ошибка `ValueError: {'code': -32000, 'message': 'invalid sender'}`
> > > > может ты сталкивался с такой
> > > 
> > > 
> > > Неа, а сама транза так же не создалась? У меня по началу с количеством газа была фигня, его мало оказалось и транзы фейлились
> > 
> > 
> > разобрался ))) там оказывается и имя функции надо было поменять, еще бы сделать баланс чтобы не целое число было и будет супер , а то палево какое то ))
> 
> 8 строчка - AMOUNT_TO_SWAP = random.randint(35, 48) но надо добавить еще import random можно зарандомить и не с целыми числами, но зачем? Ты еще палишься на газ лимите, он выставлен константой, я себе подправил, чтоб брался актуальный + 20-30% сверху, чтоб транза точно прошла Ну а по чесноку, если гонять только 2 направления - выглядит уже нехорошо в плане палева))

у меня кстати с газом вообще засада , выставил статику 800 000 , а то если меньше файлы начали вылазить , я думаю по целым числам легче вычаслить , я руками когда проходил , жмикал просто max, а там баланс всегда не ровный + комиссия забирает часть USDC , не подскажешь случайно , как ты с корректировал код для газа , где +20% , в остальном все твои советы помогли

**Comment by lionff** [comment]
> > > > > > 143 строка кода - начиная с swap_txn - polygon_w3 меняй на fantom_w3
> > > > > 
> > > > > 
> > > > > спасибо громадное , уже прогресс, пошел апрув , но к сожалению не помогло, но свап не делается, выскакивает ошибка `ValueError: {'code': -32000, 'message': 'invalid sender'}`
> > > > > может ты сталкивался с такой
> > > > 
> > > > 
> > > > Неа, а сама транза так же не создалась? У меня по началу с количеством газа была фигня, его мало оказалось и транзы фейлились
> > > 
> > > 
> > > разобрался ))) там оказывается и имя функции надо было поменять, еще бы сделать баланс чтобы не целое число было и будет супер , а то палево какое то ))
> > 
> > 
> > 8 строчка - AMOUNT_TO_SWAP = random.randint(35, 48) но надо добавить еще import random можно зарандомить и не с целыми числами, но зачем? Ты еще палишься на газ лимите, он выставлен константой, я себе подправил, чтоб брался актуальный + 20-30% сверху, чтоб транза точно прошла Ну а по чесноку, если гонять только 2 направления - выглядит уже нехорошо в плане палева))
> 
> у меня кстати с газом вообще засада , выставил статику 800 000 , а то если меньше фейлы начали вылазить , я думаю по целым числам легче вычаслить , я руками когда проходил , жмикал просто max, а там баланс всегда не ровный + комиссия забирает часть USDC , не подскажешь случайно , как ты с корректировал код для газа , где +20% , в остальном все твои советы помогли

    gasLimit = fantom_w3.eth.estimate_gas(swap_txn)
    swap_txn['gas'] = int(gasLimit + gasLimit * 0.5)

![58e3c04c9d1789750fab1c0ddd147bf9](https://user-images.githubusercontent.com/79597699/230890753-94eb7521-a63b-4561-9184-c9154168a442.png)

для полигона так же, только 

gasLimit = polygon_w3.eth.estimate_gas(swap_txn)

**Comment by CrisBTC** [comment]
> > > > > > > 143 строка кода - начиная с swap_txn - polygon_w3 меняй на fantom_w3
> > > > > > 
> > > > > > 
> > > > > > спасибо громадное , уже прогресс, пошел апрув , но к сожалению не помогло, но свап не делается, выскакивает ошибка `ValueError: {'code': -32000, 'message': 'invalid sender'}`
> > > > > > может ты сталкивался с такой
> > > > > 
> > > > > 
> > > > > Неа, а сама транза так же не создалась? У меня по началу с количеством газа была фигня, его мало оказалось и транзы фейлились
> > > > 
> > > > 
> > > > разобрался ))) там оказывается и имя функции надо было поменять, еще бы сделать баланс чтобы не целое число было и будет супер , а то палево какое то ))
> > > 
> > > 
> > > 8 строчка - AMOUNT_TO_SWAP = random.randint(35, 48) но надо добавить еще import random можно зарандомить и не с целыми числами, но зачем? Ты еще палишься на газ лимите, он выставлен константой, я себе подправил, чтоб брался актуальный + 20-30% сверху, чтоб транза точно прошла Ну а по чесноку, если гонять только 2 направления - выглядит уже нехорошо в плане палева))
> > 
> > 
> > у меня кстати с газом вообще засада , выставил статику 800 000 , а то если меньше фейлы начали вылазить , я думаю по целым числам легче вычаслить , я руками когда проходил , жмикал просто max, а там баланс всегда не ровный + комиссия забирает часть USDC , не подскажешь случайно , как ты с корректировал код для газа , где +20% , в остальном все твои советы помогли
> 
> ```
> gasLimit = fantom_w3.eth.estimate_gas(swap_txn)
> swap_txn['gas'] = int(gasLimit + gasLimit * 0.5)
> ```
> 
> ![58e3c04c9d1789750fab1c0ddd147bf9](https://user-images.githubusercontent.com/79597699/230890753-94eb7521-a63b-4561-9184-c9154168a442.png)
> 
> для полигона так же, только
> 
> gasLimit = polygon_w3.eth.estimate_gas(swap_txn)

спасибо большое , надеюсь наша переписка будет полезна всем )

**Comment by CrisBTC** [comment]
@lionff  а ты случайно не смог реализовать функцию с балансом (запрос баланса и отправка в переменную (AMOUNT_TO_SWAP) этого баланса) , а то рандомное число это очень хорошо, но очень тяжело реализовать,  чтобы средств хватало в обе стороны при первом пуске или возможно есть более изящное решение ? )))

**Comment by lionff** [comment]
А, я тебя не так понял) Вообще попробую через запрос баланса, но там так же может быть косяк с комиссиями (сам L0 отщипывает от твоей суммы транзы USDC) или я туплю
Сам скрипт такой... немного на коленке)

**Comment by ryu666zaki** [comment]
Пофиксил все ошибки что нашел(как всегда наступил с переменными), можете обновляться. Проверил лично, и теперь скрипт гоняет туда сюда без ошибок, да и не крешиться в тех случаях когда slippage сожрал пару копеек, и на транзакцию с Fantom в Polygon не хватает USDC.

Насчёт рандомизации.
Я честно говоря не вижу смысла в рандомизации сумм на отправку, так как по логике свапалок первый раз вы будете гнать определенное равное число(сумму), а назад вы по факту будете тыкать в метамаске на макс. сумму а не вводить вручную. Когда вы гоняете туда сюда транзакции каждый раз с другими(рандомными) суммами - это более подозрительно, так как, еще раз повторюсь, по статистике мало кто вручную в метамаске вводит сумму. 
Человек если захочет погонять туда сюда транзакции почти 100% тыкнет в обратную сторону на кнопку макс. сумма, а робот будет каждый раз вписывать другую сумму в заданном диапазоне.
А если вы хотите поиграться в имитацию использования моста 'по назначению', то у вас заранее ничего не получиться с помощью скрипта.
Во-первых, одна и та же сеть.
Во-вторых, транзакции гоняться через мост и обратно и больше никуда.

Хотите допилить функционал, пожалуйста, форкайте, я ни в коем случае не против)

**Comment by ryu666zaki** [comment]
> 
Обновил скрипт, теперь баланс подтягивается и проверяется перед каждой транзакцией.

**Comment by CrisBTC** [comment]
> > 
> 
> Обновил скрипт, теперь баланс подтягивается и проверяется перед каждой транзакцией.

ты лучший , спасибо за скрипт
